---
title: Spring 2018 BCJC Tech Lab
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  uploads:
    title: Uploads
    output: true
subtitle: Data Moves
description: 'Welcome to the internship website for the spring BCJC tech lab: How
  Data Moves! We''ll be learning web design principles by editing this site, and will
  post projects and resources for one another here.'
author: Maya Wagoner
email: mwagoner@bklynlibrary.org
avatar: assets/images/emerge-white.png
baseurl: ''
url: ''
facebook_url: 
github_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: 
google_analytics: 
theme: jekyll-theme-prologue
