---
title: How Data Moves Internship
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: 
description: Welcome to the internship website for the spring BCJC tech lab! We'll
  be learning web design principles by editing this site, and will post projects and
  resources for one another here.
author: Maya Wagoner
email: mwagoner@bklynlibrary.org
avatar: assets/images/emerge-white.png
baseurl: "/datamoves"
url: ''
facebook_url: 
github_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: 
google_analytics: 
theme: jekyll-theme-prologue
