---
title: How Data Moves
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    author: ''
    icon: ''
subtitle: BCJC Lab Spring 2018
description: Welcome to the internship website for the spring BCJC tech lab! We'll
  be learning web design principles by editing this site, and will post projects and
  resources for one another here.
author: Maya Wagoner
email: mwagoner@bklynlibrary.org
avatar: assets/images/emerge-white.png
baseurl: "/datamoves"
url: https://mayawagon.github.io
facebook_url: 
github_url: https://github.com/mayawagon/datamoves
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: 
google_analytics: 
theme: jekyll-theme-prologue
excerpt_separator: "<!--read more-->"
